### ISSUE TITLE
Error on 'make develop'

### ISSUE THREAD

**Issue by matthiasbeyer** [matejc/nixui#10]
Can get 'make just-run-it' working either, but this looks much more strange:

```bash
make develop
```
brings up a new bash instance (I guess it does a `nix-shell` call, right?) which brings up a window telling me:

```
Uncaught node.js Error 

Error: Cannot find module 'nedb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/m/nixui/src/data.js:4:12)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
```

**Comment by matejc** [comment]
try `make just-run-it` with latest master, I fixed few things, and at last, I will make a release and pull request for nixpkgs this week (if nothing comes in the way..)
