### ISSUE TITLE
Program crash after clicking menu item a few times 

### ISSUE THREAD

**Issue by linquize** [matejc/nixui#18]
Uncaught node.js Error 

TypeError: undefined is not a function
    at config-options.utils.fire (file:///nix/store/zpfsd8rw2n2x19s20664bjqyrkvlz9vb-nixui/lib/node_modules/nixui/bower_components/polymer/polymer.js:8996:19)
    at config-options.<anonymous> (file:///nix/store/zpfsd8rw2n2x19s20664bjqyrkvlz9vb-nixui/lib/node_modules/nixui/src/configuration.new.html:283:34)
    at /nix/store/zpfsd8rw2n2x19s20664bjqyrkvlz9vb-nixui/lib/node_modules/nixui/src/data.js:130:9
    at callback (/nix/store/di5q65xygrg9qsi2086qz934bggnggks-node-nedb-1.0.2/lib/node_modules/nedb/lib/executor.js:30:17)
    at Cursor.execFn (/nix/store/di5q65xygrg9qsi2086qz934bggnggks-node-nedb-1.0.2/lib/node_modules/nedb/lib/datastore.js:417:12)
    at Cursor._exec (/nix/store/di5q65xygrg9qsi2086qz934bggnggks-node-nedb-1.0.2/lib/node_modules/nedb/lib/cursor.js:172:17)
    at /nix/store/di5q65xygrg9qsi2086qz934bggnggks-node-nedb-1.0.2/lib/node_modules/nedb/lib/executor.js:40:13
    at Object.q.process (/nix/store/g3ljq428x89sqi34nff5rxhczcq9gzgb-node-async-0.2.10/lib/node_modules/async/lib/async.js:731:21)
    at next (/nix/store/g3ljq428x89sqi34nff5rxhczcq9gzgb-node-async-0.2.10/lib/node_modules/async/lib/async.js:728:27)
    at /nix/store/g3ljq428x89sqi34nff5rxhczcq9gzgb-node-async-0.2.10/lib/node_modules/async/lib/async.js:24:16

**Comment by matejc** [comment]
Yes, it is a known problem, it should be fixed with commit: https://github.com/matejc/nixui/commit/567b645426ac44588fd5c2db2189534bdb3d49c0

it is already in master, feel free to reopen the issue if it still happens somehow.. and thanks for reporting the issue!
